### ISSUE TITLE
PostGIS access, reloading geospatial data to server database

### ISSUE THREAD

**Issue by emiliom** [geohackweek/vector#13]
The tutorial currently (last year) uses two geospatial datasets from PostGIS:
1. `world_seas` [in the Intro notebook (cell 31)](http://nbviewer.jupyter.org/github/geohackweek/vector/blob/gh-pages/docker/notebooks/geopandas_intro.ipynb)
2. `hybas_na_lev00_v1c` [in the Advanced notebook (cell 4)](http://nbviewer.jupyter.org/github/geohackweek/vector/blob/gh-pages/docker/notebooks/geopandas_advanced.ipynb)

I need to reload them, and then ensure they have the proper access permissions. I didn't retain the instructions (commands used) from last year.

I plan to use `shp2pgsql` (or `ogr2ogr` if I run into problems):
- https://postgis.net/docs/using_postgis_dbmanagement.html#shp2pgsql_usage
- https://www.openscg.com/2017/03/importing-shapefiles-into-postgis-with-shp2pgsql/
- https://connect.boundlessgeo.com/docs/suite/4.5/dataadmin/pgGettingStarted/shp2pgsql.html
- http://www.bostongis.com/pgsql2shp_shp2pgsql_quickguide.bqg

**Comment by emiliom** [comment]
AWS system configuration: PostgreSQL 9.4.7 & POSTGIS 2.1.8

**Comment by emiliom** [comment]
#### 1. World_Seas.shp
```bash
cd <basepath1>/geopandas-tutorial-maptime/data
shp2pgsql -I -s 4326 ./World_Seas.shp World_Seas | psql -h subdomain.rds.amazonaws.com -p 5432 -U username -W -d dbname
```

#### 2. hybas_na_lev00_v1c.shp
*Note setting of geometry output column name (**-g polygongeom**), and **"-D"** option (Use the PostgreSQL "dump" format for the output data) for efficiency.*
```bash
cd <basepath2>/HydroBASINS/hybas_na_v1c
shp2pgsql -I -D -g polygongeom -s 4326 ./hybas_na_lev00_v1c.shp hybas_na_lev00_v1c | psql -q -h subdomain.rds.amazonaws.com -p 5432 -U username -W -d dbname
```

**Comment by lsetiawan** [comment]
## Testings on Jupyter Notebooks regarding POSTGIS sections.
### [geopandas_intro](https://nbviewer.jupyter.org/github/geohackweek/vector/blob/gh-pages/docker/notebooks/geopandas_intro.ipynb)

- Line 31: `geom_col` value needs to be `geom`
  ```python
  seas = GeoDataFrame.from_postgis("select * from world_seas", conn, 
                                 geom_col='geom', crs={'init': 'epsg:4326'}, 
                                 coerce_float=False)
  ```

- Testing on both python 2.7 and python 3.6 are a success!

### [geopandas_advanced](https://nbviewer.jupyter.org/github/geohackweek/vector/blob/gh-pages/docker/notebooks/geopandas_advanced.ipynb)

- Line 4: `geom_col` value needs to be `polygongeom`
  ```python
  hydrobas_ww = GeoDataFrame.from_postgis(
    "SELECT * FROM hybas_na_lev00_v1c WHERE pfaf_4 = 7831", 
    conn, geom_col='polygongeom', crs={'init': u'epsg:4326'}, 
    coerce_float=False)
  ```

- Line 9: `geometry` is now `polygongeom` in list of cols
  ```python 
  cols = ['pfaf_6', 'pfaf_7', 'geometry']
  ```

- After Line 26: Spatial join and Zonal stats are having trouble reading in `polygongeom` geometry name and column name so I added the snippet below to change the geometry name to the standard, default `geometry`.
  ```python
  # Rename geometry column to standard name of 'geometry'
  hydrobas_ww_p7 = hydrobas_ww_p7.rename(columns={'polygongeom': 'geometry'})
  hydrobas_ww_p7._geometry_column_name = 'geometry'
  ```
  

- Testing on both python 2.7 and python 3.6 are a success!

**Comment by emiliom** [comment]
Thanks! I'll look into the issue you've found with spatial join and zonal stats failing when the geometry column is not named "geometry"

**Comment by lsetiawan** [comment]
@emiliom The new release of GeoPandas seems to have the fix for error when the geometry column name is different than `geometry` for spatial join. [rasterstats](https://github.com/perrygeo/python-rasterstats/) however is still struggling in reading the geometry column other than `geometry`. 

```python
# Rename geometry column to standard name of 'geometry'
# Still needed for rasterstats to work.
hydrobas_ww_p7 = hydrobas_ww_p7.rename(columns={'polygongeom': 'geometry'})
hydrobas_ww_p7._geometry_column_name = 'geometry'
```

**Comment by emiliom** [comment]
Ok. Thanks for the update.

**Comment by lsetiawan** [comment]
## Note

Seems like Geopandas can read a default geometry column name `geom`, but anything else fails if not specified.

For example:

```python
seas = GeoDataFrame.from_postgis("select * from world_seas", conn, crs={'init': 'epsg:4326'}, 
                                 coerce_float=False)
```
The code above works, but,

```python
hydrobas_ww = GeoDataFrame.from_postgis(
    "SELECT * FROM hybas_na_lev00_v1c WHERE pfaf_4 = 7831", 
    conn, crs={'init': u'epsg:4326'}, 
    coerce_float=False)
```
gives a `ValueError`:

```python
...
//anaconda/envs/workenv/lib/python3.6/site-packages/geopandas/io/sql.py in read_postgis(sql, con, geom_col, crs, index_col, coerce_float, params)
     36     if geom_col not in df:
     37         raise ValueError("Query missing geometry column '{0}'".format(
---> 38             geom_col))
     39 
     40     wkb_geoms = df[geom_col]

ValueError: Query missing geometry column 'geom'
```

**Comment by lsetiawan** [comment]
## Update on Postgres

A readonly user for the students has been created. Credentials will be announced during the week.

**Comment by emiliom** [comment]
> A readonly user for the students has been created. Credentials will be announced during the week.

Thanks. I need to finish the vector tutorial by Monday evening, so please share with me the user name and password sometime on Monday.

**Comment by emiliom** [comment]
All taken care of. Thanks for your help on this, @lsetiawan!
