### ISSUE TITLE
Geopandas default styling and other changes.

### ISSUE THREAD

**Issue by lsetiawan** [geohackweek/vector#15]
## Geopandas_intro

When using Geopandas `GeoDataFrame.plot()`  the default styling is not pleasing. So, I'm suggesting some default style. Listing of Matplotlib Colormap can be found: https://matplotlib.org/users/colormaps.html

- `oceans.plot()` should have `cmap` argument assigned to `Set2`. This is what it looks like without:
![oceansplot](https://user-images.githubusercontent.com/17802172/30130755-23a4e112-92ff-11e7-9c54-9f8343477890.png)

- `oceans.envelope.plot()` is facing the same issue as above. `cmap` should be assigned to `Set2` and I think that `alpha` value should be assigned to `0.8` to have some opacity.

- The note about polygon boundaries coming through can be removed. 
  > NOTE/WATCH:   
The oceans polygon boundaries are coming through the world dataset! I've looked into this and can't find a solution. I think it's a bug in the GeoPandas underlying plotting library or plotting approach.

- With the new geopandas update. `GeoDataFrame.from_features()` now can read a geojson and create a GeoDataFrame. `wfs_gdf = GeoDataFrame.from_features(wfs_geo)`

**Comment by emiliom** [comment]
Yup, please adjust the styles in cases where the new default is obviously not conveying the message described in the tutorial.

I'll send you via email my current version of the two notebooks (though probably they are the Maptime, no-postgis versions), where I've already removed mention of geopandas bugs that are already fixed, and made some code updates (though not to styles), including `wfs_gdf = GeoDataFrame.from_features(wfs_geo)`

FYI, it looks like I don't get notified by default when a new issue is created in this repo. So I didn't get notified on this issue.

**Comment by lsetiawan** [comment]
> FYI, it looks like I don't get notified by default when a new issue is created in this repo. So I didn't get notified on this issue.

Hmm.. weird. I guess i should've pinged you. Thanks for the notebooks. I'll add the PostGIS stuff in.

**Comment by lsetiawan** [comment]
### Update on this issue

Default styling has been applied. Updated notebooks has been sent to @emiliom via email. Review is in progress.

**Comment by emiliom** [comment]
Notebooks have been finalized, with updates to the styles used. Note that we had to accommodate an unexpected Matplotlib version 1.5 (rather than 2.0) in the conda environment, but so be it.
