### ISSUE TITLE
Ensure notebook runs with Python 3.6, and ideally 2.7 too

### ISSUE THREAD

**Issue by emiliom** [geohackweek/vector#4]
@lsetiawan already started working on this, and it's looking good! I'm opening an issue just to help us track problems and remember to confirm compatibility

**Comment by lsetiawan** [comment]
After the tweaks listed in https://github.com/geohackweek/vector/issues/13#issuecomment-325462092. Both notebooks run with Python 3.6 and Python 2.7.

**Comment by emiliom** [comment]
Great! Thanks.

**Comment by emiliom** [comment]
Taken care of. The new environment file provided with the tutorial uses Python 3.6. Closing issue.
