### ISSUE TITLE
Site link needs to be put in

### ISSUE THREAD

**Issue by lsetiawan** [geohackweek/vector#6]
@aaarendt I think we need the live site for each of the repo to be listed on the front page of the github code page. See below.

<img width="393" alt="screenshot 2017-08-17 20 47 13" src="https://user-images.githubusercontent.com/17802172/29443512-715b54f8-838d-11e7-9b70-ee7c0bc8f320.png">

**Comment by emiliom** [comment]
I assume this issue is between you and Anthony? Therefore, I'll unwatch the issue.

**Comment by aaarendt** [comment]
Done - I didn't know about this and will add to all the tutorials. Thanks!
